repos:
  - id: /.*/
    workflow: conftest
    allowed_overrides: [workflow, apply_requirements]

workflows:
  conftest:
    plan:
      steps:
        - init
        - plan:
            extra_args: ["-out=plan.tfplan"]
        - run: /home/atlantis/.atlantis/bin/terraform1.12.2 show -json plan.tfplan | conftest test --all-namespaces -p /home/atlantis/policy -
    apply:
      steps:
        - apply
