version: "3.8"

services:
  atlantis:
    build:
      context: .
      dockerfile: Dockerfile
    image: atlantis-v0.34.0-terraform-v1.12.2
    container_name: atlantis
    environment:
      - ATLANTIS_DEFAULT_TERRAFORM_VERSION=1.12.2
    # Load environment variables from .env file
    env_file:
      - .env
    ports:
      - "4141:4141"  # Expose Atlantis UI/webhook port
    volumes:
      - atlantis-data:/home/atlantis/repos              # Use named volume
      - ./config.yaml:/etc/atlantis/config.yaml:ro      # Atlantis server-side config
      - ./policy:/home/atlantis/policy:ro               # Atlantis policy files
    command: server --repo-config=/etc/atlantis/config.yaml --port=4141
    restart: unless-stopped

volumes:
  atlantis-data:
    name: atlantis-data