version: "3.8"

services:
  atlantis:
    image: ghcr.io/runatlantis/atlantis:v0.34.0 # Stable pinned version
    container_name: atlantis
    # Load environment variables from .env file
    env_file:
      - .env
    ports:
      - "4141:4141"  # Expose Atlantis UI/webhook port
    volumes:
      - atlantis-data:/home/atlantis/repos              # Use named volume
      - ./config.yaml:/etc/atlantis/config.yaml:ro      # Atlantis server-side config
    command: server --repo-config=/etc/atlantis/config.yaml --port=4141
    restart: unless-stopped

volumes:
  atlantis-data: {}
