version: "3.8"

services:
  atlantis:
    image: ghcr.io/runatlantis/atlantis:v0.34.0 # Pinning version for stability
    container_name: atlantis
    # This directive explicitly tells Docker Compose to load variables
    # from the .env file in this directory. This is default behavior,
    # but being explicit improves clarity.
    env_file:
      - .env
    ports:
      # Map port 4141 on the host to port 4141 in the container
      - "4141:4141"
    volumes:
      # Use a named volume for persistent Atlantis data (plan files, etc.)
      - atlantis-data:/home/atlantis
      # Mount the server-side repo config to a dedicated, read-only config path
      - ./atlantis.yaml:/etc/atlantis/atlantis.yaml:ro
    command: server --repo-config=/etc/atlantis/atlantis.yaml --port=4141
    restart: unless-stopped

volumes:
  atlantis-data:
    name: atlantis-data