version: "3.8"

services:
  atlantis:
    image: runatlantis/atlantis:v0.27.2 # Pinning version for stability
    container_name: atlantis
    # This directive explicitly tells Docker Compose to load variables
    # from the .env file in this directory. This is default behavior,
    # but being explicit improves clarity.
    env_file:
      - .env
    ports:
      # Map port 4141 on the host to port 4141 in the container
      - "4141:4141"
    volumes:
      # Use a named volume for persistent Atlantis data (plan files, etc.)
      - atlantis-data:/home/atlantis
      # Mount the server-side repo config from the repo root as read-only
      - ../atlantis.yaml:/home/atlantis/atlantis.yaml:ro
    command: server --repo-config=/home/atlantis/atlantis.yaml --port=4141
    restart: unless-stopped

volumes:
  atlantis-data:
    name: atlantis-data