services:
    atlantis:
      image: runatlantis/atlantis:latest
      container_name: atlantis
      network_mode: "host"
      environment:
        - ATLANTIS_GH_USER=<github-username>
        - ATLANTIS_GH_TOKEN=<personal-access-token>
        - ATLANTIS_GH_WEBHOOK_SECRET=<random-secret>
        - ATLANTIS_REPO_ALLOWLIST=github.com/<your-org>/<repo>
      volumes:
        - ./repos:/home/atlantis/repos
        - ./atlantis.yaml:/atlantis/repos.yaml
        - ./config.yaml:/etc/atlantis/config.yaml:ro
      command: ["server", "--config", "/etc/atlantis/config.yaml"]
      restart: unless-stopped