version: "3"

services:
  atlantis:
    image: runatlantis/atlantis
    container_name: atlantis
    ports:
      - "4141:4141"
    environment:
      - ATLANTIS_GH_USER=<userid git>
      - ATLANTIS_GH_TOKEN=<token>
      - ATLANTIS_GH_WEBHOOK_SECRET=<randm secret>
      - ATLANTIS_REPO_ALLOWLIST=github.com/<userid git>/<repo name>
      - ATLANTIS_PORT=4141
    volumes:
      - ./repos:/home/atlantis/repos
      - ./terraform-sa.json:/home/atlantis/terraform-sa.json
    restart: unless-stopped